apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "solkidgal.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminUsername: {{ include "solkidgal.secretValue" (list . "adminUsername" true) | quote }}
  adminPassword: {{ include "solkidgal.secretValue" (list . "adminPassword" true) | quote }}
  sessionSecret: {{ include "solkidgal.secretValue" (list . "sessionSecret" false) | quote }}
  postgresPassword: {{ include "solkidgal.secretValue" (list . "postgresPassword" false) | quote }}
