export const defaultState = {
  coins: 100,
  energy: 84,
  vocab: 0,
  expression: 0,
  kindness: 0,
  mood: 72,
  difficulty: 100,
  speechEnabled: true,
  owned: ["softBrownHair", "starterPajama"],
  outfit: {
    hairstyle: "softBrownHair",
    top: "none",
    bottom: "none",
    dress: "starterPajama",
    outer: "none",
    shoes: "none",
    headTop: "none",
    headSide: "none",
    faceEyes: "none",
    faceMask: "none",
    neck: "none",
    hand: "none",
    room: "none"
  },
  diary: [],
  completedLessons: [],
  metNpcs: [],
  learnedWords: [],
  badges: [],
  activeQuest: null,
  area: "castle",
  player: { x: 51.5, y: 50 },
  playerNode: "princessRoom"
};
