// 衣物單品衍生式 registry 生成器（issue #267）。
// SSOT＝各包 assets/layers/<slug>.metadata.json sidecar（＋ <pack>/style.json storeId、starter/items.json）；
// 本腳本掃描衍生出 committed content-package/wardrobe/index.generated.js，runtime 只讀生成檔（純靜態相容、不 readdir）。
//
//   node scripts/genWardrobeIndex.mjs           # 重生 index.generated.js
//   node scripts/genWardrobeIndex.mjs --check   # 守門：驗素材↔sidecar 一致、id 唯一、type 合法，且 index 無漂移
//
// 生成期守門（兩模式皆跑）：每 .webp 必有同名 .metadata.json（反之亦然，無孤兒）、id 全域唯一、type 為合法 slot、targetBox 形狀合法。
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { outfitSlots, wardrobeLayerBoundsByType } from "../content-package/wardrobe/_shared/rules.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const WARDROBE = join(root, "content-package", "wardrobe");
const PACK_ORDER = ["starter", "urban", "castle", "rural", "wild"]; // 沿舊 wardrobeItems 聚合順序
const LAYER_PACKS = ["castle", "urban", "rural", "wild"];
const META_SUFFIX = ".metadata.json";
const validTypes = new Set(Object.keys(wardrobeLayerBoundsByType));
const typeRank = (t) => { const i = outfitSlots.indexOf(t); return i === -1 ? 99 : i; };

const errors = [];
const seenIds = new Set();
const layerRaw = [];

for (const pack of LAYER_PACKS) {
  const layersDir = join(WARDROBE, pack, "assets", "layers");
  const files = readdirSync(layersDir);
  const webps = new Set(files.filter((f) => f.endsWith(".webp")).map((f) => f.slice(0, -".webp".length)));
  const metas = files.filter((f) => f.endsWith(META_SUFFIX)).map((f) => f.slice(0, -META_SUFFIX.length));
  const metaSet = new Set(metas);
  const style = JSON.parse(readFileSync(join(WARDROBE, pack, "style.json"), "utf8"));
  const storeId = style.storeId;
  if (!storeId) errors.push(`${pack}/style.json 缺 storeId`);
  for (const slug of webps) if (!metaSet.has(slug)) errors.push(`${pack}/${slug}.webp 無對應 sidecar（孤兒素材）`);
  for (const slug of metas) if (!webps.has(slug)) errors.push(`${pack}/${slug}${META_SUFFIX} 無對應 .webp（孤兒 sidecar）`);
  const items = [];
  for (const slug of metas) {
    if (!webps.has(slug)) continue;
    let meta;
    try { meta = JSON.parse(readFileSync(join(layersDir, slug + META_SUFFIX), "utf8")); }
    catch (e) { errors.push(`${pack}/${slug}${META_SUFFIX} JSON 解析失敗：${e.message}`); continue; }
    if (!meta.id) errors.push(`${pack}/${slug} sidecar 缺 id`);
    else if (seenIds.has(meta.id)) errors.push(`id 重複「${meta.id}」（${pack}/${slug}）`);
    else seenIds.add(meta.id);
    if (!validTypes.has(meta.type)) errors.push(`${pack}/${slug} type「${meta.type}」非合法 slot`);
    if (meta.targetBox && ["left", "top", "right", "bottom"].some((k) => typeof meta.targetBox[k] !== "number")) {
      errors.push(`${pack}/${slug} targetBox 形狀不合法`);
    }
    const item = { pack, id: meta.id, storeId, type: meta.type, name: meta.name, cost: meta.cost, icon: meta.icon, asset: slug };
    if (meta.targetBox) item.targetBox = meta.targetBox;
    items.push(item);
  }
  items.sort((a, b) => typeRank(a.type) - typeRank(b.type) || a.id.localeCompare(b.id));
  layerRaw.push(...items);
}

const starter = JSON.parse(readFileSync(join(WARDROBE, "starter", "items.json"), "utf8"));
const starterRaw = starter.items.map((it) => {
  if (seenIds.has(it.id)) errors.push(`id 重複「${it.id}」（starter）`); else seenIds.add(it.id);
  return { pack: "starter", id: it.id, storeId: starter.storeId, type: it.type, name: it.name, cost: it.cost, icon: it.icon, asset: null };
});

const byPack = (p) => (p === "starter" ? starterRaw : layerRaw.filter((r) => r.pack === p));
const ordered = PACK_ORDER.flatMap(byPack);

if (errors.length) {
  console.error("genWardrobeIndex 守門失敗：\n- " + errors.join("\n- "));
  process.exit(1);
}

const body = ordered.map((r) => `  Object.freeze(${JSON.stringify(r)})`).join(",\n");
const out = "// AUTO-GENERATED by scripts/genWardrobeIndex.mjs —— 請勿手改。\n"
  + "// 衣物單品衍生 registry（issue #267）：自 <pack>/assets/layers/<slug>.metadata.json sidecar\n"
  + "// ＋ <pack>/style.json storeId ＋ starter/items.json 衍生。新增/移除單品＝增刪素材及其 sidecar，\n"
  + "// 再跑 `node scripts/genWardrobeIndex.mjs` 重生本檔（dev server 於內容變更後自動重生）。\n"
  + `export const wardrobeRaw = Object.freeze([\n${body}\n]);\n`;

const outPath = join(WARDROBE, "index.generated.js");
if (process.argv.includes("--check")) {
  const cur = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (cur !== out) {
    console.error("index.generated.js 與素材/ sidecar 不一致（請跑 `node scripts/genWardrobeIndex.mjs` 重生）");
    process.exit(1);
  }
  console.log(`genWardrobeIndex --check PASS：${ordered.length} 件、webp↔sidecar 一一對應、id 唯一、type 合法`);
} else {
  writeFileSync(outPath, out);
  console.log(`genWardrobeIndex：${ordered.length} 件 → content-package/wardrobe/index.generated.js`);
}
